### ISSUE TITLE
`FromStr` implementation fails parsing IBAN's with an incorrect format

### ISSUE THREAD

**Issue by alexrault** [ThomasdenH/iban_validate#44]
Hi 👋 

I've recently hit an issue that parsing a string to an `IBAN` type fails if the `IBAN` in the string is valid but incorrectly formatted.

This is best represented in this test case:

```rust
#[test]
fn test_validate() {
    assert!(iban::BaseIban::try_from("NL30 INGB 4526 31 2517").is_err());

    assert!(iban::BaseIban::try_from("NL30 INGB 4526 3125 17").is_ok());
}
```

This fails because its parsed in it's electronic form, if that fails then in it's pretty print form here: https://github.com/ThomasdenH/iban_validate/blob/master/iban_validate/src/base_iban.rs#L322

### Solution
Remove any whitespace in the string and then parse it in its electronic form - any reason not to do this?

**Comment by ThomasdenH** [comment]
Hi!

Thanks for your issue. I'm afraid it's intentional that the parser follows the IBAN standard quite strictly and only accepts the electronic and pretty print format (a space between every four characters) defined there. If you want to also accept IBANs formatted in a non-standard way, I would recommend using your workaround and strip whitespace before parsing it. Let me know if that suits your needs!
